# Generated by Django 5.1.4 on 2025-01-14 11:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tool', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Idea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='아이디어명:')),
                ('image', models.ImageField(blank=True, upload_to='uploaded_images/%Y%m%d', verbose_name='Image:')),
                ('content', models.TextField(verbose_name='아이디어 설명:')),
                ('interest', models.IntegerField(max_length=20, verbose_name='아이디어 관심도:')),
                ('devtool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tool.tool', verbose_name='예상 개발툴:')),
            ],
        ),
    ]
