# Generated by Django 5.1.4 on 2025-01-10 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='genre',
            field=models.CharField(blank=True, choices=[('action', '액션'), ('comedy', '코미디'), ('drama', '드라마'), ('fantasy', '판타지'), ('horror', '호러'), ('SF', 'SF')], max_length=10),
        ),
        migrations.AlterField(
            model_name='board',
            name='runtime',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='board',
            name='score',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='board',
            name='year',
            field=models.IntegerField(),
        ),
    ]
