# Generated by Django 5.1.4 on 2025-01-10 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_alter_board_genre_alter_board_runtime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='genre',
            field=models.CharField(blank=True, choices=[('Action', '액션'), ('Comedy', '코미디'), ('Drama', '드라마'), ('Fantasy', '판타지'), ('Horror', '호러'), ('SF', 'SF')], max_length=10),
        ),
    ]
